language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nose2
notifications:
  slack: devprogress:2qhz69Ea3JpXhvyL3IZRwUl2
cache: pip
before_install:
- openssl aes-256-cbc -K $encrypted_a3c1f8b747b9_key -iv $encrypted_a3c1f8b747b9_iv
  -in tests/data/e2e_secrets.tar.enc -out tests/data/e2e_secrets.tar -d
- tar xvf tests/data/e2e_secrets.tar -C tests/data/
