language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nose2
notifications:
  slack: devprogress:2qhz69Ea3JpXhvyL3IZRwUl2
before_install:
- openssl aes-256-cbc -K $encrypted_715cb0c531e6_key -iv $encrypted_715cb0c531e6_iv
  -in client_id.json.enc -out client_id.json -d
